version: '3.5'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    hostname: db_host
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    networks:
      - sykinet
    command: ["postgres","-c","max_connections=1500","-c","max_prepared_transactions=64","-c","log_statement=all"]

  back:
    container_name: back
    build:
      context: .
      dockerfile: Dockerfile.back
    depends_on:
      - db
    environment:
      - 'ASPNETCORE_URLS=http://+:5001'
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Database__ConnectionString=UserID=postgres;Password=postgres;Host=db_host;Port=5432;Database=syki-db;Pooling=true;'
    ports:
      - '5001:5001'
    networks:
      - sykinet

  front:
    container_name: front
    build:
      context: .
      dockerfile: Dockerfile.front
    depends_on:
      - back
    ports:
      - '5002:80'
    networks:
      - sykinet

  daemon:
    container_name: daemon
    build:
      context: .
      dockerfile: Dockerfile.daemon
    depends_on:
      - back
    environment:
      - 'ASPNETCORE_URLS=http://+:5003'
      - 'ASPNETCORE_ENVIRONMENT=Development'
      - 'Database__ConnectionString=UserID=postgres;Password=postgres;Host=db_host;Port=5432;Database=syki-db;Pooling=true;Keepalive=60;'
    ports:
      - '5003:5003'
    networks:
      - sykinet

  seq:
    image: 'datalust/seq:latest'
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
    networks:
      - sykinet

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rasykimq
    ports:
      - 15672:15672
      - 5672:5672

networks:
  sykinet:
    driver: bridge
